version: "3.8"

services:
  app:
    container_name: comic-completion
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces:cached
      - "d:/.:/data"
    tty: true
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
